; Bone Fertilizer OS — NSIS Installer
; Auto-generated by OpenCode

Unicode True
RequestExecutionLevel admin
SetCompressor lzma

!define PRODUCT_NAME "Bone Fertilizer OS"
!define PRODUCT_VERSION "1.0.0"
!define PRODUCT_PUBLISHER "BoneChain"
!define PRODUCT_EXE "BoneFertilizerApp.exe"
!define PRODUCT_DIR "$PROGRAMFILES64\${PRODUCT_NAME}"

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "BoneFertilizerApp-${PRODUCT_VERSION}-Setup.exe"
InstallDir "${PRODUCT_DIR}"

; Pages
Page directory
Page instfiles
UninstPage uninstConfirm
UninstPage instfiles

Section "Install" SecMain
  ; Binaries
  SetOutPath "$INSTDIR\bin"
  File /r "install\bin\*.*"

  ; Data
  SetOutPath "$INSTDIR\Data"
  File /r "install\Data\*"

  ; Themes
  SetOutPath "$INSTDIR\Themes"
  File /r "install\Themes\*"

  ; Assets
  SetOutPath "$INSTDIR\Assets"
  File /r "install\Assets\*"

  ; i18n
  SetOutPath "$INSTDIR\i18n"
  File /r "install\i18n\*"

  ; Shortcuts
  CreateDirectory "$SMPROGRAMS\${PRODUCT_NAME}"
  CreateShortCut "$SMPROGRAMS\${PRODUCT_NAME}\${PRODUCT_NAME}.lnk" "$INSTDIR\bin\${PRODUCT_EXE}"
  CreateShortCut "$DESKTOP\${PRODUCT_NAME}.lnk" "$INSTDIR\bin\${PRODUCT_EXE}"

  ; Uninstaller
  WriteUninstaller "$INSTDIR\Uninstall.exe"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" \
    "DisplayName" "${PRODUCT_NAME}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" \
    "UninstallString" "$INSTDIR\Uninstall.exe"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" \
    "DisplayIcon" "$INSTDIR\bin\${PRODUCT_EXE}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" \
    "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" \
    "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd

Section "Uninstall"
  ; Remove all files and dirs
  RMDir /r "$INSTDIR\bin"
  RMDir /r "$INSTDIR\Data"
  RMDir /r "$INSTDIR\Themes"
  RMDir /r "$INSTDIR\Assets"
  RMDir /r "$INSTDIR\i18n"
  Delete "$INSTDIR\Uninstall.exe"
  RMDir "$INSTDIR"

  ; Remove shortcuts
  RMDir /r "$SMPROGRAMS\${PRODUCT_NAME}"
  Delete "$DESKTOP\${PRODUCT_NAME}.lnk"

  ; Remove registry
  DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
SectionEnd
